name: model-farmers
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://iterativeai/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          dvc repro # Generar archivos necesarios

          git fetch --prune 
          dvc metrics diff --show-md master > report.md #comparar o ver la diferencia entre el nuevo archivo y la que esta en la branch
                    
          # Add figure to the report
          echo "## Validating results by region" 
          cml-publish by_region.png --md >> report.md
          
          cml-send-comment report.md